/**
 * generated by Xtext 2.10.0
 */
package dsl.xtext.ui.contentassist;

import dsl.xtext.ui.contentassist.AbstractDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
