/*
 * generated by Xtext 2.10.0
 */
package dsl.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import dsl.xtext.ide.contentassist.antlr.internal.InternalDslParser;
import dsl.xtext.services.DslGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class DslParser extends AbstractContentAssistParser {

	@Inject
	private DslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDSLAccess().getGroup(), "rule__DSL__Group__0");
					put(grammarAccess.getDSLAccess().getGroup_3(), "rule__DSL__Group_3__0");
					put(grammarAccess.getDSLAccess().getGroup_7(), "rule__DSL__Group_7__0");
					put(grammarAccess.getDSLAccess().getSyntaxesAssignment_2(), "rule__DSL__SyntaxesAssignment_2");
					put(grammarAccess.getDSLAccess().getSyntaxesAssignment_3_1(), "rule__DSL__SyntaxesAssignment_3_1");
					put(grammarAccess.getDSLAccess().getBehavioursAssignment_6(), "rule__DSL__BehavioursAssignment_6");
					put(grammarAccess.getDSLAccess().getBehavioursAssignment_7_1(), "rule__DSL__BehavioursAssignment_7_1");
					put(grammarAccess.getSyntaxAccess().getValueAssignment(), "rule__Syntax__ValueAssignment");
					put(grammarAccess.getBehaviorAccess().getValueAssignment(), "rule__Behavior__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDslParser typedParser = (InternalDslParser) parser;
			typedParser.entryRuleDSL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
