/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getPrimitiveField()
 * @model
 * @generated
 */
public interface PrimitiveField extends Field
{
} // PrimitiveField
