/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Type T</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getRealTypeT()
 * @model
 * @generated
 */
public interface RealTypeT extends TypeSystem
{
} // RealTypeT
