/**
 * generated by Xtext 2.10.0
 */
package dsl.xtext.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.xtext.dsl.DSL#getSyntaxes <em>Syntaxes</em>}</li>
 *   <li>{@link dsl.xtext.dsl.DSL#getBehaviours <em>Behaviours</em>}</li>
 * </ul>
 *
 * @see dsl.xtext.dsl.DslPackage#getDSL()
 * @model
 * @generated
 */
public interface DSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Syntaxes</b></em>' containment reference list.
   * The list contents are of type {@link dsl.xtext.dsl.Syntax}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Syntaxes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syntaxes</em>' containment reference list.
   * @see dsl.xtext.dsl.DslPackage#getDSL_Syntaxes()
   * @model containment="true"
   * @generated
   */
  EList<Syntax> getSyntaxes();

  /**
   * Returns the value of the '<em><b>Behaviours</b></em>' containment reference list.
   * The list contents are of type {@link dsl.xtext.dsl.Behavior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behaviours</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviours</em>' containment reference list.
   * @see dsl.xtext.dsl.DslPackage#getDSL_Behaviours()
   * @model containment="true"
   * @generated
   */
  EList<Behavior> getBehaviours();

} // DSL
