/**
 * generated by Xtext 2.10.0
 */
package dsl.xtext.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dsl.xtext.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.dsl/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = dsl.xtext.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link dsl.xtext.dsl.impl.DSLImpl <em>DSL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.xtext.dsl.impl.DSLImpl
   * @see dsl.xtext.dsl.impl.DslPackageImpl#getDSL()
   * @generated
   */
  int DSL = 0;

  /**
   * The feature id for the '<em><b>Syntaxes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__SYNTAXES = 0;

  /**
   * The feature id for the '<em><b>Behaviours</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__BEHAVIOURS = 1;

  /**
   * The number of structural features of the '<em>DSL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.xtext.dsl.impl.SyntaxImpl <em>Syntax</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.xtext.dsl.impl.SyntaxImpl
   * @see dsl.xtext.dsl.impl.DslPackageImpl#getSyntax()
   * @generated
   */
  int SYNTAX = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNTAX__VALUE = 0;

  /**
   * The number of structural features of the '<em>Syntax</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNTAX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.xtext.dsl.impl.BehaviorImpl <em>Behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.xtext.dsl.impl.BehaviorImpl
   * @see dsl.xtext.dsl.impl.DslPackageImpl#getBehavior()
   * @generated
   */
  int BEHAVIOR = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__VALUE = 0;

  /**
   * The number of structural features of the '<em>Behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link dsl.xtext.dsl.DSL <em>DSL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DSL</em>'.
   * @see dsl.xtext.dsl.DSL
   * @generated
   */
  EClass getDSL();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.xtext.dsl.DSL#getSyntaxes <em>Syntaxes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Syntaxes</em>'.
   * @see dsl.xtext.dsl.DSL#getSyntaxes()
   * @see #getDSL()
   * @generated
   */
  EReference getDSL_Syntaxes();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.xtext.dsl.DSL#getBehaviours <em>Behaviours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Behaviours</em>'.
   * @see dsl.xtext.dsl.DSL#getBehaviours()
   * @see #getDSL()
   * @generated
   */
  EReference getDSL_Behaviours();

  /**
   * Returns the meta object for class '{@link dsl.xtext.dsl.Syntax <em>Syntax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Syntax</em>'.
   * @see dsl.xtext.dsl.Syntax
   * @generated
   */
  EClass getSyntax();

  /**
   * Returns the meta object for the attribute '{@link dsl.xtext.dsl.Syntax#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dsl.xtext.dsl.Syntax#getValue()
   * @see #getSyntax()
   * @generated
   */
  EAttribute getSyntax_Value();

  /**
   * Returns the meta object for class '{@link dsl.xtext.dsl.Behavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behavior</em>'.
   * @see dsl.xtext.dsl.Behavior
   * @generated
   */
  EClass getBehavior();

  /**
   * Returns the meta object for the attribute '{@link dsl.xtext.dsl.Behavior#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dsl.xtext.dsl.Behavior#getValue()
   * @see #getBehavior()
   * @generated
   */
  EAttribute getBehavior_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dsl.xtext.dsl.impl.DSLImpl <em>DSL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.xtext.dsl.impl.DSLImpl
     * @see dsl.xtext.dsl.impl.DslPackageImpl#getDSL()
     * @generated
     */
    EClass DSL = eINSTANCE.getDSL();

    /**
     * The meta object literal for the '<em><b>Syntaxes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__SYNTAXES = eINSTANCE.getDSL_Syntaxes();

    /**
     * The meta object literal for the '<em><b>Behaviours</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__BEHAVIOURS = eINSTANCE.getDSL_Behaviours();

    /**
     * The meta object literal for the '{@link dsl.xtext.dsl.impl.SyntaxImpl <em>Syntax</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.xtext.dsl.impl.SyntaxImpl
     * @see dsl.xtext.dsl.impl.DslPackageImpl#getSyntax()
     * @generated
     */
    EClass SYNTAX = eINSTANCE.getSyntax();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYNTAX__VALUE = eINSTANCE.getSyntax_Value();

    /**
     * The meta object literal for the '{@link dsl.xtext.dsl.impl.BehaviorImpl <em>Behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.xtext.dsl.impl.BehaviorImpl
     * @see dsl.xtext.dsl.impl.DslPackageImpl#getBehavior()
     * @generated
     */
    EClass BEHAVIOR = eINSTANCE.getBehavior();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIOR__VALUE = eINSTANCE.getBehavior_Value();

  }

} //DslPackage
