/*
 * generated by Xtext 2.10.0
 */
package dsl.xtext.ui.tests;

import com.google.inject.Injector;
import dsl.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("dsl.xtext.Dsl");
	}

}
